//! Markdown emission of the test page.

use std::fmt::Write;

use crate::coverage::BinaryCoverage;
use crate::discover::SubcommandPath;

pub struct BinarySection {
    pub binary: String,
    pub captures: Vec<SubcommandCapture>,
}

pub struct SubcommandCapture {
    pub subcommand_path: SubcommandPath,
    pub help: String,
    pub invocation: String,
    pub output: String,
}

pub fn format_test_page(coverage: &[BinaryCoverage], sections: &[BinarySection]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Brit CLI Test Page");
    let _ = writeln!(out);
    let _ = writeln!(out, "_Auto-generated by `brit-test-page`. Do not edit by hand unless\n_you're using the `--candidate` TDD-redesign workflow._");
    let _ = writeln!(out);

    // Coverage summary
    let _ = writeln!(out, "## Coverage");
    let _ = writeln!(out);
    let _ = writeln!(out, "| Binary | Covered | Total | % |");
    let _ = writeln!(out, "|---|---|---|---|");
    for c in coverage {
        let _ = writeln!(out, "| {} | {} | {} | {}% |", c.binary, c.covered, c.total, c.percent());
    }
    let total_covered: usize = coverage.iter().map(|c| c.covered).sum();
    let total_total: usize = coverage.iter().map(|c| c.total).sum();
    let total_pct = if total_total == 0 { 100 } else { (total_covered * 100) / total_total };
    let _ = writeln!(out, "| **Total** | **{}** | **{}** | **{}%** |", total_covered, total_total, total_pct);
    let _ = writeln!(out);

    // Uncovered list per binary
    let any_uncovered: bool = coverage.iter().any(|c| !c.uncovered.is_empty());
    if any_uncovered {
        let _ = writeln!(out, "### Uncovered subcommands");
        let _ = writeln!(out);
        for c in coverage {
            for path in &c.uncovered {
                let _ = writeln!(out, "- `{}`", path.join(" "));
            }
        }
        let _ = writeln!(out);
    }

    // Per-binary sections
    for section in sections {
        let _ = writeln!(out, "## {}", section.binary);
        let _ = writeln!(out);
        for cap in &section.captures {
            let _ = writeln!(out, "### {}", cap.subcommand_path.join(" "));
            let _ = writeln!(out);
            let _ = writeln!(out, "**Help:** {}", cap.help);
            let _ = writeln!(out);
            let _ = writeln!(out, "**Invocation:**");
            let _ = writeln!(out);
            let _ = writeln!(out, "```sh");
            let _ = writeln!(out, "{}", cap.invocation);
            let _ = writeln!(out, "```");
            let _ = writeln!(out);
            let _ = writeln!(out, "**Output:**");
            let _ = writeln!(out);
            let _ = writeln!(out, "```");
            let _ = writeln!(out, "{}", cap.output.trim_end());
            let _ = writeln!(out, "```");
            let _ = writeln!(out);
        }
    }

    out
}
